# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, help_text="URL to the study groups' page", max_length=500, null=True)),
                ('location', models.CharField(blank=True, help_text='City and or state name', max_length=300, null=True)),
                ('region', models.CharField(blank=True, help_text='Asia, North America, etc.', max_length=300, null=True)),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
    ]
