# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroup',
            options={},
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='link',
            field=models.URLField(help_text="URL to the study groups' page", max_length=500),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='location',
            field=models.CharField(help_text='City and or state name', max_length=300),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='region',
            field=models.CharField(help_text='Asia, North America, etc.', max_length=300),
        ),
    ]
