# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('project_url', models.URLField(help_text="URL to the project's landing page on the web", max_length=500, null=True)),
                ('slug', models.SlugField(help_text="Slug appended to the Mozilla Science project's url that represents this project", max_length=150, null=True, verbose_name='Mozilla Science URL Slug')),
                ('github_owner', models.CharField(max_length=200)),
                ('github_repository', models.CharField(max_length=300)),
                ('image_url', models.URLField(help_text="URL to project's image.", max_length=500, null=True)),
                ('institution', models.CharField(help_text='Institution/Organization this project belongs to', max_length=300, null=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('license', models.CharField(max_length=50, null=True)),
                ('categories', models.ManyToManyField(related_name='projects', to='projects.Category')),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='projects.Tag'),
        ),
    ]
