# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160422_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='institution',
            field=models.CharField(blank=True, help_text='Institution/Organization this project belongs to', max_length=300, null=True),
        ),
    ]
