# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160422_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL to project's image.", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text="URL to the project's landing page on the web", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text="Slug appended to the Mozilla Science project's url that represents this project", max_length=150, null=True, verbose_name='Mozilla Science URL Slug'),
        ),
    ]
