# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160425_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scienctific_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(help_text="URL to project's image.", max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text="Slug appended to the Mozilla Science project's url that represents this project", max_length=150, verbose_name='Mozilla Science URL Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('Active', 'Active'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Under Review', help_text='Has this project been Approved or not', max_length=50),
        ),
    ]
