# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160427_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL to project's image.", max_length=500, null=True),
        ),
    ]
