# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('github_id', models.IntegerField(null=True)),
                ('github_username', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar_url', models.URLField(blank=True, help_text="URL to user's avatar", max_length=500, null=True)),
                ('blog', models.URLField(blank=True, help_text="URL to user's blog", max_length=500, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
    ]
