# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160425_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserProject', to='projects.Project'),
        ),
    ]
