# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160426_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Contributor', 'Contributor')], default='Contributor', max_length=20),
        ),
    ]
