# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160427_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Volunteer', 'Volunteer')], default='Volunteer', max_length=20),
        ),
    ]
