# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image_url', models.URLField(blank=True, help_text="URL to an event's image.", max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text="Slug appended to the Mozilla Science event's url that represents this event", max_length=150, null=True, verbose_name='Mozilla Science URL Slug')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
    ]
