# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160425_1615'),
        ('users', '0002_user'),
        ('events', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events_attended', to='users.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to='users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='facilitators',
            field=models.ManyToManyField(blank=True, related_name='events_facilitated', to='users.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='events', to='projects.Project'),
        ),
    ]
