# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160425_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
