# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='This appears below the photo in the full-page view; should be distinct from the "short description"', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, help_text='This appears below the photo in the card pre-view, and below the title in the full-page view', max_length=300, null=True),
        ),
    ]
