# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-12 17:16
from __future__ import unicode_literals

from django.db import migrations


def fill_timezones(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        event.timezone = 'UTC'
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170605_1624'),
    ]

    operations = [
        migrations.RunPython(fill_timezones)
    ]
