# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170612_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_created']},
        ),
    ]
